# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: unknown                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Beispiel Plugin für SmartHomeNG v1.8 und höher'
        en: 'Sample plugin for SmartHomeNG v1.8 and up'
    maintainer: <autor>
#    tester:                         # Who tests this plugin?
    state: develop                  # Initial 'develop'. change to 'ready' when done with development
#    keywords: iot xyz
#    documentation: ''              # An url to optional plugin doc - NOT the url to user_doc!!!
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.10              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    suspendable: false              # plugin can be suspended, must be implemented in code
    classname: SamplePlugin         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)

    # item to toggle suspend mode
    suspend_item:
        type: str
        default: ''
        description:
            de: 'Item zum Schalten des Suspend-Modus'
            en: 'item for toggling suspend mode'

    param1:
        type: str
        description:
            de: 'Demo Parameter'
            en: 'Parameter for demonstration purposes'

    param2:
        type: str
        default: 'value2'
        valid_list:
            - 'value1'
            - 'value2'
            - 'value3'
            - 'value4'
            - 'value5'
        description:
            de: 'Demo Parameter mit Gültigkeitsliste und Standardwert'
            en: 'Demonstration parameter with valid-list and default value'

    param3:
        type: str
        # If 'mandatory' is specified, a 'default' attribute must not be specified
        mandatory: true
        description:
            de: 'Demo Parameter der angegeben werden muss'
            en: 'Demonstration parameter which has to be specified'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
