#!/usr/bin/env bash
# install-hooks.sh — install git quality-gate hooks for SmartHomeNG repos.
#
# Usage (from the shng root or from tools/ directly):
#   tools/install-hooks.sh
#
# The script asks whether to install hooks for core, plugins, or both.
# To update existing hooks after changes, simply re-run the script.
#
# Hooks installed:
#   pre-commit  format staged .py files with ruff format (auto-applied),
#               then hard-gate on ruff check
#   pre-push    hard-gate on pytest (shng: tests/ only; plugins: . from plugins root)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHNG_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ ! -f "$SHNG_DIR/tox.ini" ] || [ ! -d "$SHNG_DIR/lib/item" ]; then
    echo "ERROR: $SHNG_DIR does not look like a SmartHomeNG root (tox.ini / lib/item missing)."
    exit 1
fi

RUFF_BIN="${SHNG_DIR}/venvs/shng/bin/ruff"
PYTEST_BIN="${SHNG_DIR}/venvs/shng/bin/pytest"

echo ""
echo "SmartHomeNG git hook installer"
echo "  shng root: $SHNG_DIR"
echo "  ruff     : $([ -x "$RUFF_BIN" ] && echo "$RUFF_BIN" || echo "ruff (from PATH)")"
echo "  pytest   : $([ -x "$PYTEST_BIN" ] && echo "$PYTEST_BIN" || echo "pytest (from PATH)")"
echo ""

# ---------------------------------------------------------------------------
# Ask which repos to configure
# ---------------------------------------------------------------------------
echo "Install hooks for:"
echo "  c) shng core only"
echo "  p) plugins only"
echo "  b) both (default)"
echo ""
read -rp "Choice [b]: " choice
choice="${choice:-b}"
echo ""

INSTALL_CORE=false
INSTALL_PLUGINS=false
case "$choice" in
    c|C) INSTALL_CORE=true ;;
    p|P) INSTALL_PLUGINS=true ;;
    b|B|"") INSTALL_CORE=true; INSTALL_PLUGINS=true ;;
    *)
        echo "Unknown choice '$choice' — use c, p, or b."
        exit 1
        ;;
esac

# ---------------------------------------------------------------------------
# 1. shng core — activate committed .githooks/
# ---------------------------------------------------------------------------
if $INSTALL_CORE; then
    echo "=== shng core: activating .githooks/ ==="

    SHNG_HOOKS_DIR="$SHNG_DIR/.githooks"
    if [ ! -d "$SHNG_HOOKS_DIR" ]; then
        echo "  ERROR: $SHNG_HOOKS_DIR not found — is the repo complete?"
        exit 1
    fi

    chmod +x "$SHNG_HOOKS_DIR/pre-commit" "$SHNG_HOOKS_DIR/pre-push"
    git -C "$SHNG_DIR" config core.hooksPath .githooks
    echo "  git config core.hooksPath .githooks  → done"
    echo "  hooks: pre-commit (format + lint gate), pre-push (pytest gate)"

    # Remove legacy post-commit if still present
    if [ -f "$SHNG_HOOKS_DIR/post-commit" ]; then
        rm "$SHNG_HOOKS_DIR/post-commit"
        echo "  removed: .githooks/post-commit (superseded by pre-commit)"
    fi
    echo ""
fi

# ---------------------------------------------------------------------------
# 2. plugins repo — write hooks into .git/hooks/
# ---------------------------------------------------------------------------
if $INSTALL_PLUGINS; then
    DEFAULT_PLUGINS="${SHNG_DIR}/plugins"
    read -rp "Plugins repository [$DEFAULT_PLUGINS]: " PLUGINS_DIR_INPUT
    PLUGINS_DIR="${PLUGINS_DIR_INPUT:-$DEFAULT_PLUGINS}"

    # Normalise to absolute path
    if [[ "$PLUGINS_DIR" != /* ]]; then
        PLUGINS_DIR="$(cd "$PLUGINS_DIR" 2>/dev/null && pwd)" || {
            echo "ERROR: Cannot resolve path '$PLUGINS_DIR'."
            exit 1
        }
    fi

    if [ ! -d "$PLUGINS_DIR/.git" ]; then
        echo "ERROR: $PLUGINS_DIR is not a git repository (.git not found)."
        exit 1
    fi

    echo ""
    echo "=== plugins: writing hooks to $PLUGINS_DIR/.git/hooks/ ==="

    HOOKS_DIR="$PLUGINS_DIR/.git/hooks"

    # -- pre-commit (format + lint gate) -----------------------------------
    cat > "$HOOKS_DIR/pre-commit" << HOOK
#!/usr/bin/env bash
# pre-commit — format and lint staged Python files.
# Generated by tools/install-hooks.sh in the shng repo — re-run to update.

PLUGINS_DIR="\$(git rev-parse --show-toplevel)"
cd "\$PLUGINS_DIR" || exit 1

RUFF="${RUFF_BIN}"
[ -x "\$RUFF" ] || RUFF="ruff"

STAGED=\$(git diff --cached --name-only --diff-filter=ACM | grep '\.py\$' || true)

if [ -z "\$STAGED" ]; then
    exit 0
fi

# --force-exclude: ruff's [tool.ruff] exclude only applies during directory
# discovery, not to explicit file paths (which is what xargs passes here).
echo "\$STAGED" | xargs "\$RUFF" format --force-exclude --quiet && echo 'Formatted.'
echo "\$STAGED" | xargs git add

if ! echo "\$STAGED" | xargs "\$RUFF" check --force-exclude; then
    echo ""
    echo "==> COMMIT REJECTED: ruff found lint errors in staged files."
    echo ""
    echo "    Fix the errors above, then:  git commit"
    echo "    Bypass (use sparingly):      git commit --no-verify"
    echo ""
    echo "    Note: ruff is a required CI check — errors will block your PR."
    exit 1
fi
HOOK

    # -- pre-push (pytest gate) --------------------------------------------
    cat > "$HOOKS_DIR/pre-push" << HOOK
#!/usr/bin/env bash
# pre-push — run plugin tests before pushing.
# Generated by tools/install-hooks.sh in the shng repo — re-run to update.

PLUGINS_DIR="\$(git rev-parse --show-toplevel)"
cd "\$PLUGINS_DIR" || exit 1

PYTEST="${PYTEST_BIN}"
[ -x "\$PYTEST" ] || PYTEST="pytest"

echo ""
echo "── pre-push gate (plugins) ─────────────────────────────────────"
echo "  running tests ..."
echo ""

if ! "\$PYTEST" --tb=short -q; then
    echo ""
    echo "==> PUSH REJECTED: tests failed."
    echo ""
    echo "    Fix failing tests, then:  git push"
    echo "    Bypass (use sparingly):   git push --no-verify"
    echo ""
    echo "    Note: pytest is a required CI check — failures will block your PR."
    echo "────────────────────────────────────────────────────────────────"
    echo ""
    exit 1
fi

echo "  pytest: OK"
echo "────────────────────────────────────────────────────────────────"
echo ""
HOOK

    chmod +x "$HOOKS_DIR/pre-commit" "$HOOKS_DIR/pre-push"

    # Remove legacy post-commit if present
    if [ -f "$HOOKS_DIR/post-commit" ]; then
        rm "$HOOKS_DIR/post-commit"
        echo "  removed: post-commit (superseded by pre-commit)"
    fi

    echo "  pre-commit (format + lint gate) → written"
    echo "  pre-push   (pytest gate)        → written"
    echo ""
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "Installation complete."
echo ""
echo "To bypass a hook for a specific commit or push (use sparingly):"
echo "  git commit --no-verify"
echo "  git push --no-verify"
echo ""
echo "Note: CI checks in GitHub Actions are mandatory — bypassing hooks"
echo "locally does not bypass the CI gate on pull requests."
echo ""
