#!/bin/bash

#########################################################################
# Copyright 2023-       Martin Sinn                         m.sinn@gmx.de
#########################################################################
#  This file is part of SmartHomeNG
#
#  SmartHomeNG is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#########################################################################

# get directory where this script is stored
DIR=$(dirname "$0")

cd $DIR
cd ..

chmod +x bin/smarthome.py

chmod +x tools/make_venv
chmod +x tools/act

chmod +x tools/build_requirements.py
chmod +x tools/check_plugin.py
chmod +x tools/conf_to_yaml_converter.py
chmod +x tools/getshngpid
chmod +x tools/measure_cpu_speed.py
chmod +x tools/plugin_metadata_checker.py
chmod +x tools/test_running
chmod +x tools/install_plugin_from_develop

chmod +x tools/esphome_install
chmod +x tools/esphome_update
chmod +x tools/esphome_start

#echo `pwd`
#find . -type d -exec chmod g+rwsx {} +
#find . -type f -exec chmod g+r {} +
#find . -name '*.ini' -exec chmod g+rw {} +
#find . -name '*.var' -exec chmod g+rw {} +


